// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCATPps-IL2heR7NqPcNNOC0F0Y_hZ6bZI',
    appId: '1:455902212910:web:a94f040a1b805a499240bf',
    messagingSenderId: '455902212910',
    projectId: 'uas-salaya',
    authDomain: 'uas-salaya.firebaseapp.com',
    storageBucket: 'uas-salaya.firebasestorage.app',
    measurementId: 'G-GTTMD9PKGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOtQafrZadkvcXHrpilMvaJvMq_ewTFAg',
    appId: '1:455902212910:android:929b2c97aee565659240bf',
    messagingSenderId: '455902212910',
    projectId: 'uas-salaya',
    storageBucket: 'uas-salaya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp7wlijcyeIxYptXX_HoHToUQmqatLf9M',
    appId: '1:455902212910:ios:5f9ab6a26437ae399240bf',
    messagingSenderId: '455902212910',
    projectId: 'uas-salaya',
    storageBucket: 'uas-salaya.firebasestorage.app',
    iosBundleId: 'com.example.uas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp7wlijcyeIxYptXX_HoHToUQmqatLf9M',
    appId: '1:455902212910:ios:5f9ab6a26437ae399240bf',
    messagingSenderId: '455902212910',
    projectId: 'uas-salaya',
    storageBucket: 'uas-salaya.firebasestorage.app',
    iosBundleId: 'com.example.uas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCATPps-IL2heR7NqPcNNOC0F0Y_hZ6bZI',
    appId: '1:455902212910:web:933c31d121c161b19240bf',
    messagingSenderId: '455902212910',
    projectId: 'uas-salaya',
    authDomain: 'uas-salaya.firebaseapp.com',
    storageBucket: 'uas-salaya.firebasestorage.app',
    measurementId: 'G-NMZS7JYQBK',
  );
}
